import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "UI Design System Development",
    description: "Create a comprehensive and scalable design system for your product. We'll develop a complete UI kit with reusable components, style guides, and documentation to ensure consistency across your applications.",
    price: 15000000,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5",
    category: "Design System",
  },
  {
    id: 2,
    name: "Mobile App UX Design",
    description: "Transform your app idea into an intuitive mobile experience. Our UX design service includes user research, wireframing, prototyping, and comprehensive user testing to ensure optimal user engagement.",
    price: 12000000,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c",
    category: "Mobile Design",
  },
  {
    id: 3,
    name: "Website UI Redesign",
    description: "Revitalize your web presence with a modern UI redesign. We'll create a fresh, engaging interface that aligns with current design trends while maintaining your brand identity and improving user experience.",
    price: 8500000,
    image: "https://images.unsplash.com/photo-1522542550221-31fd19575a2d",
    category: "Web Design",
  },
  {
    id: 4,
    name: "UX Research & Analysis",
    description: "Get deep insights into your users' needs and behaviors. Our research service includes user interviews, usability testing, analytics review, and detailed recommendations for improving your product's UX.",
    price: 7500000,
    image: "https://images.unsplash.com/photo-1553028826-f4804a6dba3b",
    category: "UX Research",
  },
  {
    id: 5,
    name: "Interactive Prototype Development",
    description: "Bring your ideas to life with high-fidelity interactive prototypes. We create clickable prototypes that simulate the real user experience, perfect for testing and stakeholder presentations.",
    price: 6500000,
    image: "https://images.unsplash.com/photo-1559028012-481c04fa702d",
    category: "Prototyping",
  },
  {
    id: 6,
    name: "Brand Identity Design",
    description: "Establish a strong visual identity for your digital product. We'll create a comprehensive brand guide including logo design, color schemes, typography, and visual elements that reflect your brand personality.",
    price: 9000000,
    image: "https://images.unsplash.com/photo-1524002232583-94b5055c8a86",
    category: "Branding",
  },
  {
    id: 7,
    name: "E-commerce UX Optimization",
    description: "Optimize your e-commerce platform for better conversion rates. We'll analyze your current user flow and implement UX improvements to reduce friction and increase sales.",
    price: 11000000,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
    category: "E-commerce",
  },
  {
    id: 8,
    name: "Design Workshop & Training",
    description: "Empower your team with UI/UX design skills. Our workshops cover design thinking, user research methods, prototyping tools, and modern design practices.",
    price: 5500000,
    image: "https://images.unsplash.com/photo-1558403194-611308249627",
    category: "Training",
  },
  {
    id: 9,
    name: "Backend API Development",
    description: "Hubungkan sistem Anda dengan mudah melalui layanan Backend API kami. Kami ahli dalam membangun API yang scalable, aman, dan memungkinkan integrasi seamless dengan berbagai layanan pihak ketiga.",
    price: 6500000,
    image: "https://images.unsplash.com/photo-1623479322729-28b25c16b011",
    category: "Backend Development",
  },
  {
    id: 10,
    name: "DevOps Implementation",
    description: "Optimalkan proses development dan deployment dengan layanan DevOps kami. Kami membangun infrastruktur yang automated, scalable, dan reliable untuk meningkatkan efisiensi tim development Anda.",
    price: 8000000,
    image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb",
    category: "DevOps",
  },
  {
    id: 11,
    name: "WordPress Development",
    description: "Bangun presence online Anda dengan layanan WordPress Development kami. Kami menciptakan website yang customized, SEO-friendly, dan mudah dikelola sesuai kebutuhan bisnis Anda.",
    price: 3500000,
    image: "https://images.unsplash.com/photo-1606857521015-7f9fcf423740",
    category: "Web Development",
  },
  {
    id: 12,
    name: "Data Analytics Dashboard",
    description: "Visualisasikan data bisnis Anda dengan Dashboard Analytics yang interaktif. Kami membangun solusi yang memudahkan Anda menganalisis dan mengambil keputusan berdasarkan data real-time.",
    price: 7500000,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
    category: "Data Analytics",
  },
  {
    id: 13,
    name: "Cloud Migration Service",
    description: "Modernisasi infrastruktur IT Anda dengan layanan Cloud Migration kami. Kami membantu transisi sistem Anda ke cloud dengan aman, efisien, dan tanpa gangguan pada operasional bisnis.",
    price: 9800000,
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
    category: "Cloud Services",
  },
  {
    id: 14,
    name: "Progressive Web App Development",
    description: "Tingkatkan engagement pengguna dengan Progressive Web App yang powerful. Kami membangun aplikasi web yang dapat diakses offline dan memberikan pengalaman seperti aplikasi native.",
    price: 5500000,
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3",
    category: "Web Development",
  },
  {
    id: 15,
    name: "Microservices Architecture",
    description: "Tingkatkan skalabilitas sistem Anda dengan arsitektur Microservices. Kami membangun sistem yang modular, mudah dimaintain, dan dapat dikembangkan secara independen sesuai kebutuhan.",
    price: 9900000,
    image: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a",
    category: "Backend Development",
  },
  {
    id: 16,
    name: "AI/ML Integration",
    description: "Optimalkan proses bisnis Anda dengan integrasi AI/ML yang powerful. Kami membantu mengimplementasikan solusi machine learning yang dapat meningkatkan efisiensi dan memberikan insights berharga.",
    price: 9950000,
    image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb",
    category: "AI Development",
  },
];

// Helper function to format price in IDR
export const formatPrice = (price: number) => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
};
