import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "UI Design System Development",
    description: "Create a comprehensive and scalable design system for your product. We'll develop a complete UI kit with reusable components, style guides, and documentation to ensure consistency across your applications.",
    price: 15000000,
    image: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e",
    category: "Design System",
  },
  {
    id: 2,
    name: "Mobile App UX Design",
    description: "Transform your app idea into an intuitive mobile experience. Our UX design service includes user research, wireframing, prototyping, and comprehensive user testing to ensure optimal user engagement.",
    price: 12000000,
    image: "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1",
    category: "Mobile Design",
  },
  {
    id: 3,
    name: "Website UI Redesign",
    description: "Revitalize your web presence with a modern UI redesign. We'll create a fresh, engaging interface that aligns with current design trends while maintaining your brand identity and improving user experience.",
    price: 8500000,
    image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8",
    category: "Web Design",
  },
  {
    id: 4,
    name: "UX Research & Analysis",
    description: "Get deep insights into your users' needs and behaviors. Our research service includes user interviews, usability testing, analytics review, and detailed recommendations for improving your product's UX.",
    price: 7500000,
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12",
    category: "UX Research",
  },
  {
    id: 5,
    name: "Interactive Prototype Development",
    description: "Bring your ideas to life with high-fidelity interactive prototypes. We create clickable prototypes that simulate the real user experience, perfect for testing and stakeholder presentations.",
    price: 6500000,
    image: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c",
    category: "Prototyping",
  },
  {
    id: 6,
    name: "Brand Identity Design",
    description: "Establish a strong visual identity for your digital product. We'll create a comprehensive brand guide including logo design, color schemes, typography, and visual elements that reflect your brand personality.",
    price: 9000000,
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0",
    category: "Branding",
  },
  {
    id: 7,
    name: "E-commerce UX Optimization",
    description: "Optimize your e-commerce platform for better conversion rates. We'll analyze your current user flow and implement UX improvements to reduce friction and increase sales.",
    price: 11000000,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
    category: "E-commerce",
  },
  {
    id: 8,
    name: "Design Workshop & Training",
    description: "Empower your team with UI/UX design skills. Our workshops cover design thinking, user research methods, prototyping tools, and modern design practices.",
    price: 5500000,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40",
    category: "Training",
  },
  {
    id: 9,
    name: "Design System Audit & Optimization",
    description: "Evaluate and enhance your existing design system. We'll analyze your current components, identify inconsistencies, and provide recommendations for improvement to ensure better design efficiency.",
    price: 6500000,
    image: "https://images.unsplash.com/photo-1434626881859-194d67b2b86f",
    category: "Design System",
  },
  {
    id: 10,
    name: "User Journey Mapping",
    description: "Visualize and optimize your users' experience through comprehensive journey mapping. We'll identify pain points, opportunities, and create detailed user flow documentation to improve your product.",
    price: 8000000,
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634",
    category: "UX Research",
  },
  {
    id: 11,
    name: "Micro-interactions Design",
    description: "Enhance your user interface with delightful micro-interactions. We'll design and document subtle animations and transitions that provide feedback and improve the overall user experience.",
    price: 3500000,
    image: "https://images.unsplash.com/photo-1618788372246-79faff0c3742",
    category: "UI Design",
  },
  {
    id: 12,
    name: "Accessibility Audit & Implementation",
    description: "Make your digital product accessible to all users. We'll conduct a thorough accessibility audit and implement WCAG guidelines to ensure your product is inclusive and compliant.",
    price: 7500000,
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984",
    category: "Accessibility",
  },
  {
    id: 13,
    name: "Design System Documentation",
    description: "Create comprehensive documentation for your design system. We'll develop detailed guidelines, component usage rules, and maintain a living style guide for your team.",
    price: 9800000,
    image: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e",
    category: "Design System",
  },
  {
    id: 14,
    name: "Mobile App Design Patterns",
    description: "Implement best-practice mobile design patterns for your app. We'll create intuitive navigation systems and interaction patterns that follow platform-specific guidelines.",
    price: 5500000,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c",
    category: "Mobile Design",
  },
  {
    id: 15,
    name: "Design QA & Testing",
    description: "Ensure pixel-perfect implementation of your designs. We'll conduct thorough design quality assurance across devices and provide detailed reports for development team alignment.",
    price: 9900000,
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12",
    category: "Quality Assurance",
  },
  {
    id: 16,
    name: "UX Writing & Content Strategy",
    description: "Craft clear and effective UX copy for your interface. We'll develop a consistent voice and tone, create microcopy guidelines, and optimize content for better user engagement.",
    price: 9950000,
    image: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c",
    category: "UX Writing",
  },
];

// Helper function to format price in IDR
export const formatPrice = (price: number) => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
};
